"""
Django settings for betfair project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import socket
import sys
import django_heroku
import pymongo
from pymongo import MongoClient
import urllib.parse
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'y1s5(bqdrzcveh%=-r6#+m7n-@rn%7f3wkmn4dztp0qr&v!vn)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Application definition

INSTALLED_APPS = [
    # 'admin_interface',
    # 'colorfield',
    'sslserver',
    'bootstrap_admin',
    # 'admin_black.apps.AdminBlackConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'db_table',
    # 'webservices',
    # 'betfaircms',
    'rest_framework.authtoken',
    'rest_framework',
    'corsheaders',
    'import_export',
    'webservices.apps.WebservicesConfig',
    
    
    

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',

]

AUTH_USER_MODEL = 'db_table.Users'

#AUTHENTICATION_BACKENDS = ('db_table.backends.DualAuthentication',)

ROOT_URLCONF = 'betfair.urls'

TEMPLATES = [
    {
        
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR , 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'betfair.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }


# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',
#         'NAME': 'sports',
#     }
# }
# DATABASES = {
# 'default': {
#         'ENGINE': 'djongo',
#         'NAME': 'sports',
#         'CLIENT': {
#             'host': "44.195.135.131:27017"
#         },   
#     },
# }
#import mongoengine


user = urllib.parse.quote_plus('rabi')
passwd = urllib.parse.quote_plus('Password123@')

DATABASES = {
'default': {
        'ENGINE': 'djongo',
        'NAME': 'sports',
        'CLIENT': {
            'host': "mongodb+srv://rabi:" + urllib.parse.quote_plus('Password123@') + "@cluster0.gtkp9.mongodb.net/sports?retryWrites=true&w=majority"
        },   
    },
}
# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

DATE_INPUT_FORMATS = ('%m-%d-%Y')
DATETIME_INPUT_FORMATS = (
    '%Y-%m-%d %H:%M:%S',   
)
ELASTIC_SEARCH_URL = 'http://soccerfrontend.myvtd.site:9200/'
ALLOWED_HOSTS=['*']
CORS_ORIGIN_ALLOW_ALL = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/


STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

MEDIA_ROOT=os.path.join(BASE_DIR,'media')
MEDIA_URL = '/media/'

IMAGE_ROOT=os.path.join(BASE_DIR,'images')
IMAGE_URL = '/images/' 

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'rabi.mtcg@gmail.com'
EMAIL_HOST_PASSWORD = '9439224370'

# django_heroku.settings(locals())
# IMPORT_EXPORT_USE_TRANSACTIONS =  False
# AUTH_PASSWORD_VALIDATORS = []
